// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetAllClient():Promise<Array<models.Client>>;

export function GetAllPrestamo():Promise<Array<models.PrestamoPlus>>;

export function SaveClient(arg1:models.Client):Promise<void>;

export function SavePrestamo(arg1:models.Prestamo):Promise<void>;
