// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllClient() {
  return window['go']['main']['App']['GetAllClient']();
}

export function GetAllLoanTable() {
  return window['go']['main']['App']['GetAllLoanTable']();
}

export function GetClientPopUp(arg1) {
  return window['go']['main']['App']['GetClientPopUp'](arg1);
}

export function GetLoan(arg1) {
  return window['go']['main']['App']['GetLoan'](arg1);
}

export function GetQuotasForMonth(arg1) {
  return window['go']['main']['App']['GetQuotasForMonth'](arg1);
}

export function SaveClient(arg1) {
  return window['go']['main']['App']['SaveClient'](arg1);
}

export function SaveLoan(arg1) {
  return window['go']['main']['App']['SaveLoan'](arg1);
}

export function UpdateLoan(arg1) {
  return window['go']['main']['App']['UpdateLoan'](arg1);
}
