// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllClient() {
  return window['go']['main']['App']['GetAllClient']();
}

export function SaveClient(arg1) {
  return window['go']['main']['App']['SaveClient'](arg1);
}

export function SavePrestamo(arg1) {
  return window['go']['main']['App']['SavePrestamo'](arg1);
}
