// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetAllClient():Promise<Array<models.Client>>;

export function GetAllPrestamoTable():Promise<Array<models.PrestamoTable>>;

export function GetClientPopUp(arg1:string):Promise<models.ClientPopUp>;

export function GetPrestamo(arg1:string):Promise<models.Prestamo>;

export function SaveClient(arg1:models.Client):Promise<void>;

export function SavePrestamo(arg1:models.PrestamoBrought):Promise<void>;

export function UpdatePrestamo(arg1:models.Prestamo):Promise<void>;
